### ISSUE TITLE
Include `rev` keyword pointing to latest version in README snippet 

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-pre-commit-hook#17]
## Problem statement

The snippet in the README is missing the `rev`  keyword, as a new user of pre-commit, it would throw me an error `missing required key: rev` which would be hard to resolve if i didn't know `rev` is to be pointed to a version.

Can we update the documentation with the fix?
```
---
repos:
  - repo: https://github.com/thoth-station/test-thoth-pre-commit-hook
    rev: v0.1.0
    hooks:
      - id: thoth-advise
        args: ["--recommendation-type", "security"]
````
